# Generated by Django 3.0.6 on 2020-06-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('table', models.CharField(max_length=20)),
                ('op', models.CharField(max_length=1)),
                ('user', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Breeds',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('emergencies', models.BooleanField()),
                ('admission', models.DateField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Address')),
            ],
            options={
                'verbose_name_plural': 'Medics',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('administration', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Address')),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('name', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('description', models.CharField(max_length=50)),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('anesthesia', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Surgeries',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Medic')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Shift')),
            ],
            options={
                'verbose_name_plural': 'WorkingShifts',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='default.png', upload_to='')),
                ('date_first_attended', models.DateField()),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Breed')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Owner')),
                ('primary_care_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Medic')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Species')),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Owner_CellPhone',
            fields=[
                ('cellphone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vet.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Medic_CellPhone',
            fields=[
                ('cellphone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vet.Medic')),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Breed')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Disease')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Medicine')),
            ],
            options={
                'verbose_name_plural': 'Diseases and Medication',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=50)),
                ('booked', models.DateField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Medic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Patient')),
                ('surgery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Surgery')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Administrators',
            },
        ),
    ]
