# Generated by Django 3.0.6 on 2020-06-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic_cellphone',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Medic'),
        ),
        migrations.AlterField(
            model_name='owner_cellphone',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='medic_cellphone',
            unique_together={('medic', 'cellphone')},
        ),
        migrations.AlterUniqueTogether(
            name='owner_cellphone',
            unique_together={('owner', 'cellphone')},
        ),
    ]
