# Generated by Django 3.0.6 on 2020-06-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_auto_20200624_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diseases',
            unique_together={('breed', 'disease', 'medication')},
        ),
    ]
