# Generated by Django 3.0.6 on 2020-06-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_auto_20200624_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='duration',
            field=models.DurationField(),
        ),
    ]
