# Generated by Django 3.0.6 on 2020-06-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_auto_20200624_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
