# Generated by Django 3.0.6 on 2020-06-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0006_auto_20200624_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('start', 'end', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('name', 'family')},
        ),
        migrations.AlterUniqueTogether(
            name='workingshift',
            unique_together={('shift', 'medic', 'date')},
        ),
    ]
