# Generated by Django 3.0.6 on 2020-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0008_auto_20200624_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
